// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aksesuarcim.Data;

#nullable disable

namespace aksesuarcim.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230928173730_38")]
    partial class _38
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("aksesuarcim.Models.Admin", b =>
                {
                    b.Property<int>("admin_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("admin_Id"), 1L, 1);

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("admin_Id");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("aksesuarcim.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Productsproduct_Id")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("Productsproduct_Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("aksesuarcim.Models.Orders", b =>
                {
                    b.Property<int>("order_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("order_Id"), 1L, 1);

                    b.Property<int>("order_amount")
                        .HasColumnType("int");

                    b.Property<int>("product_Id")
                        .HasColumnType("int");

                    b.HasKey("order_Id");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("aksesuarcim.Models.Products", b =>
                {
                    b.Property<int>("product_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("product_Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Ordersorder_Id")
                        .HasColumnType("int");

                    b.Property<string>("criterion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("discount")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("product_Code")
                        .HasColumnType("int");

                    b.Property<string>("product_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("product_price")
                        .HasColumnType("int");

                    b.Property<int>("shoppingId")
                        .HasColumnType("int");

                    b.Property<string>("union")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("product_Id");

                    b.HasIndex("Ordersorder_Id");

                    b.HasIndex("shoppingId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("aksesuarcim.Models.Shopping", b =>
                {
                    b.Property<int>("shoppingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("shoppingId"), 1L, 1);

                    b.Property<int>("order_amount")
                        .HasColumnType("int");

                    b.Property<int>("product_Id")
                        .HasColumnType("int");

                    b.HasKey("shoppingId");

                    b.ToTable("shoppings");
                });

            modelBuilder.Entity("aksesuarcim.Models.Category", b =>
                {
                    b.HasOne("aksesuarcim.Models.Products", "Products")
                        .WithMany("Categories")
                        .HasForeignKey("Productsproduct_Id");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("aksesuarcim.Models.Products", b =>
                {
                    b.HasOne("aksesuarcim.Models.Orders", "Orders")
                        .WithMany()
                        .HasForeignKey("Ordersorder_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aksesuarcim.Models.Shopping", "Shopping")
                        .WithMany("products")
                        .HasForeignKey("shoppingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("Shopping");
                });

            modelBuilder.Entity("aksesuarcim.Models.Products", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("aksesuarcim.Models.Shopping", b =>
                {
                    b.Navigation("products");
                });
#pragma warning restore 612, 618
        }
    }
}
